config = [
    {
        "name": "account1",
        "proxy": "",
        "clientBuildNumber": "your_data",
        "clientMasteringNumber": "your_data",
        "clientId": "your_data",
        "dsid": "your_data",
        "cookies": {
            'X_APPLE_WEB_KB-<your_data>': 'your_data',
            'X-APPLE-WEBAUTH-USER': 'your_data',
            'X-APPLE-WEBAUTH-HSA-TRUST': 'your_data',
            'X-APPLE-DS-WEB-SESSION-TOKEN': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Events': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Documents': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Photos': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Cloudkit': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Safari': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Mail': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Notes': 'your_data',
            'X-APPLE-WEBAUTH-PCS-News': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Sharing': 'your_data',
            'X-APPLE-WEB-ID': 'your_data',
            'X-APPLE-WEBAUTH-VALIDATE': 'your_data',
            'X-APPLE-WEBAUTH-TOKEN': 'your_data',
        },
        "headers": {
            'Accept': '*/*',
            'Accept-Language': 'en-US,en;q=0.9,ru;q=0.8',
            'Connection': 'keep-alive',
            'Content-Type': 'text/plain',
            'Origin': 'https://www.icloud.com',
            'Referer': 'https://www.icloud.com/',
            'Sec-Fetch-Dest': 'empty',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-site',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
            'sec-ch-ua': '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
        }
    },
    {
        "name": "account2",
        "proxy": "",
        "clientBuildNumber": "your_data",
        "clientMasteringNumber": "your_data",
        "clientId": "your_data",
        "dsid": "your_data",
        "cookies": {
            'X_APPLE_WEB_KB-<your_data>': 'your_data',
            'X-APPLE-WEBAUTH-USER': 'your_data',
            'X-APPLE-WEBAUTH-HSA-TRUST': 'your_data',
            'X-APPLE-DS-WEB-SESSION-TOKEN': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Events': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Documents': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Photos': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Cloudkit': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Safari': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Mail': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Notes': 'your_data',
            'X-APPLE-WEBAUTH-PCS-News': 'your_data',
            'X-APPLE-WEBAUTH-PCS-Sharing': 'your_data',
            'X-APPLE-WEB-ID': 'your_data',
            'X-APPLE-WEBAUTH-VALIDATE': 'your_data',
            'X-APPLE-WEBAUTH-TOKEN': 'your_data',
        },
        "headers": {
            'Accept': '*/*',
            'Accept-Language': 'en-US,en;q=0.9,ru;q=0.8',
            'Connection': 'keep-alive',
            'Content-Type': 'text/plain',
            'Origin': 'https://www.icloud.com',
            'Referer': 'https://www.icloud.com/',
            'Sec-Fetch-Dest': 'empty',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-site',
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
            'sec-ch-ua': '"Not A(Brand";v="8", "Chromium";v="132", "Google Chrome";v="132"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
        }
    }
]
